[
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly completed",
        "ts": "1548233480.000100",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly started, skipdecks=False",
        "ts": "1548233485.000200",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly completed",
        "ts": "1548268770.000300",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly started, skipdecks=False",
        "ts": "1548268774.000400",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-01-23 23:07:47,744 ERROR Somehow Sphere of Safety got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,745 ERROR Somehow Plains got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,746 ERROR Somehow Ghostly Prison got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,746 ERROR Somehow Mystic Monastery got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,746 ERROR Somehow Curse of Vitality got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,747 ERROR Somehow Windborn Muse got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,747 ERROR Somehow Tranquil Cove got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,748 ERROR Somehow Wind-Scarred Crag got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,748 ERROR Somehow Sigil of the Empty Throne got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,748 ERROR Somehow Mesa Enchantress got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,749 ERROR Somehow Azorius Signet got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,749 ERROR Somehow Boros Signet got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,750 ERROR Somehow Plea for Guidance got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,750 ERROR Somehow Assemble the Legion got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,750 ERROR Somehow Blazing Archon got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,751 ERROR Somehow Return to Dust got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,751 ERROR Somehow Gwafa Hazid, Profiteer got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,752 ERROR Somehow Lightmine Field got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,752 ERROR Somehow Sun Titan got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,753 ERROR Somehow Luminarch Ascension got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,753 ERROR Somehow Gisela, Blade of Goldnight got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,753 ERROR Somehow Azorius Guildgate got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,754 ERROR Somehow Boros Guildgate got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,754 ERROR Somehow Blind Obedience got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,755 ERROR Somehow Aurification got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,755 ERROR Somehow Vow of Duty got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,755 ERROR Somehow Underworld Connections got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,756 ERROR Somehow Auramancer got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,756 ERROR Somehow Boros Battleshaper got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,757 ERROR Somehow Isperia, Supreme Judge got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,757 ERROR Somehow Deflecting Palm got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,757 ERROR Somehow Monk Idealist got into this set of recs ['R', 'U'] (cmdr matrix)\n2019-01-23 23:07:47,758 ERROR Somehow Jeskai Ascendancy got into this set of recs ['R', 'U'] (cmdr matrix)\n```",
        "ts": "1548284818.000500",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly completed",
        "ts": "1548302749.000600",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly started, skipdecks=False",
        "ts": "1548302753.000700",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-01-24 04:45:19,626 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \"\/usr\/lib\/python3.5\/code.py\", line 64, in runsource\n    code = self.compile(source, filename, symbol)\n  File \"\/usr\/lib\/python3.5\/codeop.py\", line 168, in __call__\n    return _maybe_compile(self.compiler, source, filename, symbol)\n  File \"\/usr\/lib\/python3.5\/codeop.py\", line 99, in _maybe_compile\n    raise err1\n  File \"\/usr\/lib\/python3.5\/codeop.py\", line 87, in _maybe_compile\n    code1 = compiler(source + \"\\n\", filename, symbol)\n  File \"\/usr\/lib\/python3.5\/codeop.py\", line 133, in __call__\n    codeob = compile(source, filename, symbol, self.flags, 1)\n  File \"&lt;console&gt;\", line 1\n    data['repls]\n               ^\nSyntaxError: EOL while scanning string literal\n```",
        "ts": "1548305069.000800",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-01-24 04:46:19,647 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \"\/usr\/lib\/python3.5\/code.py\", line 91, in runcode\n    exec(code, self.locals)\n  File \"&lt;console&gt;\", line 1, in &lt;module&gt;\nImportError: No module named 'cards'\n```",
        "ts": "1548305129.000900",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[24\/Jan\/2019:06:17:29] HTTP \nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/core\/cache.py\", line 56, in get\n    _CACHE[key] = json.loads(rec['value'])\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cachetools\/ttl.py\", line 91, in __setitem__\n    self.expire(time)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cachetools\/ttl.py\", line 171, in expire\n    cache_delitem(self, curr.key)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cachetools\/cache.py\", line 73, in __delitem__\n    del self.__data[key]\nKeyError: 'wp\/by-category\/content'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/wordpress.py\", line 52, in index\n    'articles': wordpress.get_posts_by_category('articles')[:7],\n  File \"\/home\/ubuntu\/edhrec\/core\/wordpress.py\", line 207, in get_posts_by_category\n    return cache.get('wp\/by-category\/{}'.format(category))\n  File \"\/home\/ubuntu\/edhrec\/core\/cache.py\", line 58, in get\n    _CACHE[key] = rec['value']\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cachetools\/ttl.py\", line 91, in __setitem__\n    self.expire(time)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cachetools\/ttl.py\", line 171, in expire\n    cache_delitem(self, curr.key)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cachetools\/cache.py\", line 73, in __delitem__\n    del self.__data[key]\nKeyError: 'wp\/by-category\/content'\n```",
        "ts": "1548310598.001000",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/37d58\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    }
]